# IDM API Swagger
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: IDM Rest API
  description: Document Storage and more
  version: "1.0.0"
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
paths:
  /document-templates:
    get:
      summary: gets the templates for a document
      description: |
        This gives us back a list of document templates
      tags:
        - Documents
      responses:
        200:
          description: An array of document templates
          schema:
            type: array
            items:
              $ref: '#/definitions/document-template'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  document-template:
    type: object
    properties:
      name:
        type: string
        description: the name of the document template
      description:
        type: string
        description: Description of document template.
      display-name:
        type: string
        description: Display name of document template.
      items:
        type: array
        items:
          $ref: '#/definitions/idm-document'
  idm-document:
    type: object
    properties:
      name:
        type: string
        description: the name of the document template
      description:
        type: string
        description: Description of document template.
      display-name:
        type: string
        description: Display name of document template.
      document-template-id:
        type: string
        description: ID of the template for this document
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
